import type { Century } from '../data/centuries'
import data from '../data/persons.json'
import type { Person, Trait } from '../data/types'
import { imageEvidence } from '../data/image-provenance'

export const PERSONS = data.persons as Person[]

const byId = new Map(PERSONS.map((person) => [person.id, person]))

export function getPerson(id: string): Person | undefined {
  return byId.get(id)
}

export function personsOf(century: Century): Person[] {
  return PERSONS.filter((person) => person.century === century)
}

export function lifespan(person: Person): string {
  if (person.lifespanLabel) return person.lifespanLabel
  if (person.deathUnknown) return `${person.born}–death date unknown`
  return person.died === null ? `born ${person.born}` : `${person.born}–${person.died}`
}

export function isLiving(person: Person): boolean {
  return person.died === null && !person.deathUnknown
}

const TRAIT_PLURALS: Record<Trait, string> = {
  writer: 'writers',
  philosopher: 'philosophers',
  scientist: 'scientists',
  mathematician: 'mathematicians',
  'head of state': 'heads of state',
  'military leader': 'military leaders',
  activist: 'activists',
  innovator: 'innovators',
}

export function traitPlural(trait: Trait): string {
  return TRAIT_PLURALS[trait]
}

export type ImageKind = 'portraits' | 'works'
export const IMAGE_WIDTHS = [480, 960] as const
export type ImageWidth = (typeof IMAGE_WIDTHS)[number]

/** Optimized images are generated by `npm run images` as `<id>-<width>.webp`. */
export function imageSrc(kind: ImageKind, id: string, width: ImageWidth = 480): string {
  if (imageEvidence(id, kind).withheld) return collectionMarker(kind, id)
  return `${import.meta.env.BASE_URL}images/${kind}/${id}-${width}.webp`
}

export function imageSrcSet(kind: ImageKind, id: string): string {
  if (imageEvidence(id, kind).withheld) return ''
  return IMAGE_WIDTHS.map((width) => `${imageSrc(kind, id, width)} ${width}w`).join(', ')
}

/** Deliberately abstract, code-drawn marker: never an invented historical likeness. */
function collectionMarker(kind: ImageKind, id: string): string {
  const person = getPerson(id)
  const initials = (person?.name ?? id).split(/[\s-]+/).slice(0, 2).map((word) => word[0]).join('')
  const safeInitials = initials.replace(/[<>&"']/g, '')
  const hue = [...id].reduce((sum, character) => sum + character.charCodeAt(0), 0) % 360
  const label = kind === 'portraits' ? 'PORTRAIT NOT VERIFIED' : 'WORK IMAGE NOT VERIFIED'
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 600"><defs><radialGradient id="g"><stop stop-color="hsl(${hue},25%,28%)"/><stop offset="1" stop-color="#171b23"/></radialGradient></defs><rect width="480" height="600" fill="url(#g)"/><g fill="none" stroke="#c9af78" opacity=".5"><circle cx="240" cy="260" r="135"/><circle cx="240" cy="260" r="116"/><path d="M65 260h350M240 85v350"/></g><text x="240" y="283" text-anchor="middle" fill="#eee3cd" font-family="Georgia,serif" font-size="72">${safeInitials}</text><text x="240" y="450" text-anchor="middle" fill="#eee3cd" font-family="sans-serif" font-size="16" letter-spacing="2">${label}</text><text x="240" y="479" text-anchor="middle" fill="#c9bfae" font-family="sans-serif" font-size="14">Collection marker · not a historical image</text></svg>`
  return `data:image/svg+xml,${encodeURIComponent(svg)}`
}
