import type { Century } from '../data/centuries'

export interface Track {
  src: string
  title: string
  composer: string
  performer: string
  license: string
  sourceUrl?: string
}

export const NEXT_WING_TRACK: Track = {
  src: `${import.meta.env.BASE_URL}audio/next-wing.m4a`,
  title: 'Tomorrow, Together',
  composer: 'Century Museum',
  performer: 'Original ambient electronic composition',
  license: 'Synthesised for this project · no external samples',
}

/** Excerpts are generated by scripts/build-soundscapes.mjs. */
const excerpt = (century: Century) => `${import.meta.env.BASE_URL}audio/${century}.m4a`

export const TRACKS: Record<Century, Track> = {
  '1600s': {
    src: excerpt('1600s'),
    title: 'Te Deum, H. 146: Prelude',
    composer: 'Marc-Antoine Charpentier (c. 1690)',
    performer: 'Ian Dollins',
    license: 'CC0',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Charpentier,_Te_Deum_(Prelude).ogg',
  },
  '1700s': {
    src: excerpt('1700s'),
    title: 'Goldberg Variations, BWV 988: Aria',
    composer: 'Johann Sebastian Bach (1741)',
    performer: 'Kimiko Ishizaka',
    license: 'CC0',
    sourceUrl:
      'https://commons.wikimedia.org/wiki/File:Kimiko_Ishizaka_-_J.S._Bach-_-Open-_Goldberg_Variations,_BWV_988_(Piano)_-_01_Aria.mp3',
  },
  '1800s': {
    src: excerpt('1800s'),
    title: 'Nocturne in E-flat major, Op. 9 No. 2',
    composer: 'Frédéric Chopin (1832)',
    performer: 'Frank Lévy for Musopen',
    license: 'Public domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Chopin_-_Nocturne_No._2_in_E-flat_major,_Op._9_No._2_(Frank_Levy).flac',
  },
  '1900s': {
    src: excerpt('1900s'),
    title: 'Clair de lune, from Suite bergamasque',
    composer: 'Claude Debussy (1905)',
    performer: 'Laurens Goedhart',
    license: 'Public domain',
    sourceUrl: 'https://commons.wikimedia.org/wiki/File:Clair_de_lune_(Claude_Debussy)_Suite_bergamasque.ogg',
  },
}
